[package]
name = "codeberg-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cod"
path = "src/main.rs"

[dependencies]
cod-bin = { version = "0.1.0", path = "crates/cod-bin" }
tokio = { version = "1.24.2", features = ["full"] }

[workspace]
members = [
  "crates/*"
]
