branches: main

clone:
  clone:
    image: woodpeckerci/plugin-git
    commands: 
      - git init -b main
      - git remote add origin https://codeberg.org/RobWalt/codeberg-cli.git 
      - git fetch origin
      - env | grep DRONE
      - |
        # current branch isn't main
        if [ -z "$DRONE_SOURCE_BRANCH" ]; then 
          # choose main
          CURRENT_BRANCH=$DRONE_BRANCH
        else 
          # choose PR branch
          CURRENT_BRANCH=$DRONE_SOURCE_BRANCH
        fi
      - echo $CURRENT_BRANCH
      - git checkout $CURRENT_BRANCH
      - git log --oneline -n 10

pipeline:
  check_commits:
    image: rust
    commands:
      - rustup default stable
      - cargo install cocogitto
      - cog check
