branches: main

clone:
  clone:
    image: woodpeckerci/plugin-git
    commands: 
      - git init -b main
      - git remote add origin https://codeberg.org/RobWalt/codeberg-cli.git 
      - git fetch origin
      - env
      - if [[ -z $DRONE_SOURCE_BRANCH ]]; then 
          CURRENT_BRANCH=$DRONE_BRANCH
        fi
      - echo $CURRENT_BRANCH
      - git checkout $CURRENT_BRANCH
      - git log --oneline -n 10

pipeline:
  abc:
    image: rust
    commands: 
      - echo "hi"
