branches: main

clone:
  clone:
    image: woodpeckerci/plugin-git
    commands: 
      - git init -b main
      - git remote add origin https://codeberg.org/RobWalt/codeberg-cli.git 
      - git fetch origin
      - env | grep BRANCH
      - git checkout $CI_COMMIT_SOURCE_BRANCH
      - git log --oneline -n 10

pipeline:
  check_commits:
    image: rust
    commands:
      - rustup default stable
      - cargo install cocogitto
      - cog check
