branches: main

clone:
  clone:
    image: woodpeckerci/plugin-git
    commands: 
      - git init -b main
      - git remote add origin https://codeberg.org/RobWalt/codeberg-cli.git 
      - git fetch origin
      - env | grep will-delete
      - git checkout $CI_COMMIT_SOURCE_BRANCH
      - git log --oneline -n 10

pipeline:
  abc:
    image: rust
    commands: 
      - echo "hi"
