branches: main

clone:
  clone:
    image: woodpeckerci/plugin-git
    commands: 
      - git init -b main
      - git remote add origin https://codeberg.org/RobWalt/codeberg-cli.git 
      - git pull origin "+$CI_COMMIT_REF:"

pipeline:
  check_commits:
    image: rust
    commands:
      - rustup default stable
      - cargo install cocogitto
      - cog check
